### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by SteveShaffer** [kdzwinel/Redmine-Issues-Checker#1]
It doesn't seem to connect to my Redmine instance.  I have REST enabled and I'm logged in.  It goes to my homepage (well, the custom page I typed in) when I click on it just fine, but it won't seem to connect.

Sorry, I don't really know what other info to give besides that.  PM me (or however that works on here, I'm new to GitHub) if you'd like the address of my instance.

Thanks.  Your tools looks awesome if I could get it work.  For the time being, it's a nice shortcut for me... :)

**Comment by kdzwinel** [comment]
I'm happy to hear that you enjoy the shortcut function :) Lets try to make other stuff work. From the top of my head: you said that you have REST enabled, so I'm guessing that you filled up the login/password fields on the options page. Remove them, restart the browser, log in to redmine (via website) and see what happens. Are you using https (I never really checked https)? Do you have a smooth connection with your redmine or is it a bit slow (connection timeout is set to 5sec)? What version of redmine are you using?

If everything fails you can do one more thing (it may be a bit challenging though):
- go to chrome://extensions/
- select the 'developer mode'
- find Redmine extension and click on background.html
- it will open a webdeveloper toolbar, take a look at 'network' and 'console' tabs for some interesting stuff (e.g. connection errors)

Keep me posted!

**Comment by SteveShaffer** [comment]
I meant that I've got the REST API enabled and I put in my username/password.  But I've tried it both ways and it didn't work.

From the logs, looks like it's 404ing on users/current.json.  I get a 404 on manually trying to get it too.

I'm running on Redmine 1.0.5.stable (MySQL).  ...which I guess is apparently not the most current version. Thought I got something more current than that.  I guess maybe that's the issue then?

Thanks for the response.

**Comment by kdzwinel** [comment]
Version 1.0 has a very [limited API](http://www.redmine.org/projects/redmine/wiki/Rest_api) that doesn't let the extension to check the ID of a current user (and this is needed to access user issues). All redmine 1.1+ versions should be fine though. I'll think about making 1.0 compatibility mode available to set via options panel.

**Comment by SteveShaffer** [comment]
I see.  Thanks for the info.  1.0 compatibility would be cool, but I'll probably think about upgrading soon anyway.  I didn't know I was behind the times; I just spun this thing up a month ago.  I guess that's what happens with these new cloud-deploy things...

Thanks for the responses!
