### ISSUE TITLE
Notifications not working on Chrome 35.0.1916.114 m

### ISSUE THREAD

**Issue by vinciferr** [kdzwinel/Redmine-Issues-Checker#10]
None of the notification options are working on Chrome 35.0.1916.114 m

**Comment by kdzwinel** [comment]
Thanks for report, I'll have a look.

**Comment by ctroncoso** [comment]
@vinciferr check your URL
It MUST end with "/"
Right: http://redmine.mysite.com/
Wrong: http://redmine.mysite.com

@kdzwinel, you might need a regexp to check on the sintax of the entered url, or notification checkmark to the right of the URL textbox (green OK | red FAILED) on loosefocus

**Comment by ArnaudLigny** [comment]
Probably linked to  #11.

**Comment by kdzwinel** [comment]
Resolved in 0.71.
