### ISSUE TITLE
Notifications not working in chrome (Version 37.0.2062.103 m)

### ISSUE THREAD

**Issue by dhanaoeindia** [kdzwinel/Redmine-Issues-Checker#12]
Iam using windows 7 and the chrome version-37.0.2062.103 m.  Notifications is not working. Even the test notification is not working. Iam using the standard and not the extended. I have also tried both the options, but it is not working. Even the test notification is not working. Please help. Cheers!

**Comment by kdzwinel** [comment]
Resolved in 0.71.
