### ISSUE TITLE
Custom request page

### ISSUE THREAD

**Issue by Regul777** [kdzwinel/Redmine-Issues-Checker#2]
Add custom request page at settings in `function getIssuesCount()`.
For me, for example, better to monitor resolved tasks of other developers and check it, instead of my tasks.
I can add this feature by my self, but require access to repository for update.

**Comment by kdzwinel** [comment]
Cool, just fork my repo, implement the feature and send me a pull request. I'll include your code.

**Comment by Regul777** [comment]
Hey, it's too long. In reality - all that we need - it's the customization of redmine api url - that's all! No need extra setup plugins. Better to release small feature than creating super function with no-release.

**Comment by kdzwinel** [comment]
It's ready - could you test it please before I deploy it in Chrome Web Store? I don't use redmine anymore and I only tested it on demo.redmine.org. Let me know if you find any errors!
- download the file ( https://dl.dropbox.com/u/8989748/Redmine-Issues-Checker-06.zip )
- unpack it
- open extensions page ( chrome://chrome/extensions )
- click 'developer mode'
- click 'load unpacked extension'
- choose directory with unpacked extension

**Comment by Regul777** [comment]
Everything work well! Options page looks very cool! I didn't detect any problem.

**Comment by kdzwinel** [comment]
Changes were deployed to Chrome Web Store. Thanks for help, I mentioned your contribution in the 'About' tab of config page.
