### ISSUE TITLE
REST interface API key support

### ISSUE THREAD

**Issue by chrisy** [kdzwinel/Redmine-Issues-Checker#4]
Any chance of having it use the user API key with the REST interface, rather than username/password?

**Comment by kdzwinel** [comment]
Hi Chris! Sure, I'll look into that. I'm currently working on version 0.6 of the extension (see branches) and the feature list is closed, but your idea sounds like nice feature to have in the next version (0.7).

**Comment by kdzwinel** [comment]
Resolved in 0.71.
