### ISSUE TITLE
Supress notifications

### ISSUE THREAD

**Issue by mt3o** [kdzwinel/Redmine-Issues-Checker#6]
Is there any way to supress all notifications of the issue checker? They are annoying... I set all kind of notification settings to off but i still receive popups about connection or logging problems. However sometimes it connects with no problem.
So, is there a way to disable them all?

**Comment by kdzwinel** [comment]
I looked into the code and there are no connection notifications. Only notifications you can get are about new issues, and you can turn these off on the options page. Icon animation and color is only indicator of connection failing. So, I'm a bit confused here. Are you sure that notifications you are complaining about are from this extension? Do you have any other redmine related extensions installed? Can you provide the text that appears on the popup?

**Comment by mt3o** [comment]
Aaaaa! :D Shame on me, you're right! 
Sorry to bother and thx for quick reply :D
Best regards

**Comment by kdzwinel** [comment]
No problem, Cheers :)
