### ISSUE TITLE
Base URL requires a / at the end

### ISSUE THREAD

**Issue by ajungren** [kdzwinel/Redmine-Issues-Checker#7]
The "Enter your redmine base URL" field in the settings requires a slash at the end of it, but that's not documented. In fact, the example given doesn't have a slash either. Without the slash, if the base URL is `http://example.com` the extension tries to load `http://example.commy/page` when the button is clicked. Adding `/` to the end of the base URL fixes it. The extension should either document this or (preferably) insert a slash when one isn't given.

**Comment by kdzwinel** [comment]
Ayron, you are right. I'll make sure to append slash when needed. Fix should be available this week. Thanks for the bug report!

**Comment by dcondrey** [comment]
By default the 'When pressed go to' field is filled with `/my/page` but the forward-slash before my is not accurate because the base URL does not work unless you include a forward slash on the end.  So apparently the slash before my is not actually being used when the url is rendered.

**Comment by kdzwinel** [comment]
Resolved in 0.71.
