### ISSUE TITLE
Not work on version 2.4

### ISSUE THREAD

**Issue by Ragaga** [kdzwinel/Redmine-Issues-Checker#9]
Redmine version          2.4.1.stable
  Ruby version                2.0.0-p353 (2013-11-22) [i686-linux]
  Rails version                 3.2.15

Hi. On vesion 2.4 extension not show count issues. Icon is stay gray with "question" icon.

**Comment by gonetil** [comment]
+1
Redmine version                2.4.2.stable.12844
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               Mysql2

**Comment by gonetil** [comment]
I think you need to activate REST web service in your-redmine.com/settings?tab=authentication

**Comment by kdzwinel** [comment]
Hi guys. Firstly, please make sure that you have REST enabled (as @gonetil suggested). If extension still wouldn't work then give me a shout, I'll be happy to fix it.
There is one little issue though. I'm not using Redmine anymore and I don't have any way to test the extension (there is a demo on redmine website, but it has REST API turned off). If any of you can provide me with access to some kind of Redmine (with REST API enabled), or (even better) is able to provide a fix for this bug, I'll be glad to deploy it.

**Comment by mfkenson** [comment]
just wanna say the current version on chrome store works with redmine 2.5.2.stable.
